version: "3"

services:
  gizmo-postgres:
    image: postgres
    container_name: gizmo-postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:consistent
    logging:
      options:
        max-size: "50m"

  gizmo-api:
    build: ./
    container_name: gizmo-api
    depends_on:
      - gizmo-postgres
    restart: always
    expose:
      - 3000
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=gizmo-postgres
    logging:
      options:
        max-size: "50m"
