version: "3"

services:
  the-sonosynthesiser-postgres:
    image: postgres
    container_name: the-sonosynthesiser-postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:consistent
    logging:
      options:
        max-size: "50m"

  the-sonosynthesiser-api:
    build: ./
    container_name: the-sonosynthesiser-api
    depends_on:
      - the-sonosynthesiser-postgres
    restart: always
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=the-sonosynthesiser-postgres
    logging:
      options:
        max-size: "50m"
